import { useState } from 'react'
import { FileText, Mic, PenLine } from 'lucide-react'
import { toast } from 'sonner'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import type { Post } from '../types'

interface ComposerDialogProps { open: boolean; onOpenChange: (open: boolean) => void; author: string; initials: string; onPost: (post: Post) => void; preset?: string }
export function ComposerDialog({ open, onOpenChange, author, initials, onPost, preset }: ComposerDialogProps) {
  const [text, setText] = useState('')
  const [type, setType] = useState(preset ?? 'Pitch')
  function post() { if (!text.trim()) return; onPost({ id: `new-${Date.now()}`, name: author, initials, kind: 'investor', headline: 'Bridgeway member · Network', time: 'Just now', body: text.trim(), tags: [], interested: 0, comments: 0, engagementScore: 0, createdAt: Date.now() }); setText(''); onOpenChange(false); toast('Posted (demo)') }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-xl rounded-2xl"><DialogHeader><DialogTitle>Share with your network</DialogTitle></DialogHeader><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-full bg-[#14213D] text-sm font-bold text-white">{initials}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{author}</p><p className="text-xs text-[#64748B]">Posting to Bridgeway</p></div><Select value={type} onValueChange={setType}><SelectTrigger className="w-[150px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Pitch">Pitch</SelectItem><SelectItem value="Memo">Memo</SelectItem><SelectItem value="Success story">Success story</SelectItem></SelectContent></Select></div><textarea value={text} onChange={(event) => setText(event.target.value.slice(0, 1500))} placeholder="What do you want to share?" className="mt-4 min-h-40 w-full resize-y rounded-xl border border-[#E5E7EB] p-3 text-sm outline-none focus:ring-2 focus:ring-[#3F4FA0]" /><div className="flex items-center justify-between text-xs text-[#64748B]"><button onClick={() => toast('Attachments are coming soon')} className="inline-flex items-center gap-2 rounded-lg border border-[#E5E7EB] px-3 py-2"><FileText className="size-4" /> Attach deck</button><span>{text.length}/1500</span></div><div className="mt-4 flex justify-end"><button disabled={!text.trim()} onClick={post} className="rounded-full bg-[#F5B544] px-6 py-2 text-sm font-bold text-[#14213D] disabled:opacity-50">Post</button></div></DialogContent></Dialog>
}

export function ComposerCard({ onOpen }: { onOpen: (preset?: string) => void }) {
  return <section className="rounded-2xl border border-[#E5E7EB] bg-white p-4 shadow-[0_3px_14px_rgba(20,33,61,0.06)] sm:p-5"><div className="flex items-center gap-3"><span className="relative grid size-10 shrink-0 place-items-center rounded-full bg-[#14213D] text-xs font-bold text-white">TM<i className="absolute -bottom-0.5 -right-0.5 size-3 rounded-full border-2 border-white bg-[#5BA4E6]" /></span><button onClick={() => onOpen()} className="h-10 min-w-0 flex-1 truncate rounded-full border border-[#E5E7EB] bg-[#F8FAFC] px-4 text-left text-xs text-[#64748B]">Share an idea, allocation or investment mandate…</button></div><div className="mt-3 grid grid-cols-3 border-t border-[#F1F3F6] pt-3">{[[Mic, 'Pitch', 'bg-[#FEF3D8] text-[#8A5A00]'], [FileText, 'Media & Deck', 'bg-[#EEF0FA] text-[#3F4FA0]'], [PenLine, 'Write memo', 'bg-[#F3EEFA] text-[#7C5CBF]']].map(([Icon, label, color]) => { const ItemIcon = Icon as typeof Mic; const title = label as string; return <button key={title} onClick={() => onOpen(title === 'Write memo' ? 'Memo' : title)} className="flex min-h-11 items-center justify-center gap-2 text-[11px] font-semibold text-[#475569] sm:text-xs"><span className={`grid size-7 place-items-center rounded-full ${color as string}`}><ItemIcon className="size-3.5" /></span><span className="truncate">{title}</span></button> })}</div></section>
}
