import { useState } from 'react'
import { Check, Clock3, FileText, Globe2, Heart, MessageCircle, MoreHorizontal, Repeat2, Send, Share2, Star, ThumbsUp } from 'lucide-react'
import { toast } from 'sonner'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import type { Post } from '../types'

export function PostCard({ post, onHide }: { post: Post; onHide: (id: string) => void }) {
  const [liked, setLiked] = useState(false)
  const [connected, setConnected] = useState(false)
  const [commentsOpen, setCommentsOpen] = useState(false)
  const [comments, setComments] = useState(['Thanks for sharing this update!', 'Impressive progress. Let’s connect.'])
  const [comment, setComment] = useState('')
  const [requested, setRequested] = useState(false)
  const [requesting, setRequesting] = useState(false)
  const count = post.interested
  function action(label: string) { toast(`${label} is coming soon (demo)`) }
  function requestRoom() { if (requesting || requested) return; setRequesting(true); window.setTimeout(() => { setRequesting(false); setRequested(true); toast('Deal room requested (demo)') }, 800) }
  return <article className="min-w-0 overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-[0_3px_14px_rgba(20,33,61,0.06)]">
    <div className="flex min-w-0 items-start gap-3 p-4 sm:p-5"><span className={`grid size-11 shrink-0 place-items-center rounded-full ${post.kind === 'investor' ? 'bg-[#14213D]' : 'bg-[#14213D] ring-2 ring-[#F5B544]'} text-xs font-bold text-white sm:size-12`}>{post.initials}</span><div className="min-w-0 flex-1"><div className="flex min-w-0 flex-wrap items-center gap-x-2 gap-y-1"><span className="text-sm font-bold">{post.name}</span><span className={`rounded-full px-2 py-0.5 text-[9px] font-bold ${post.kind === 'founder' ? 'bg-[#FEF3D8] text-[#8A5A00]' : 'bg-[#3F4FA0] text-white'}`}>{post.kind.toUpperCase()}</span><span className="text-[11px] text-[#94A3B8]">· {post.id === 'marcus' || post.id === 'apex' ? '2nd' : '1st'}</span></div><p className="line-clamp-2 text-xs text-[#64748B]">{post.headline}</p><p className="mt-0.5 flex items-center gap-1 text-[10px] text-[#94A3B8]">{post.time} · <Globe2 className="size-3" /></p></div><button onClick={() => { setConnected((value) => !value); if (!connected) toast('Connection request sent (demo)') }} className={`flex h-9 shrink-0 items-center gap-1 rounded-full px-3 text-[11px] font-semibold ${connected ? 'bg-[#F1F3F6] text-[#64748B]' : 'bg-[#EEF0FA] text-[#3F4FA0]'}`} aria-label={connected ? 'Cancel pending connection' : 'Connect'}>{connected ? <><Clock3 className="size-3.5" /><span className="hidden sm:inline">Pending</span></> : <><span className="hidden sm:inline">+ Connect</span><span className="sm:hidden">+</span></>}</button><DropdownMenu><DropdownMenuTrigger asChild><button aria-label="Post options" className="grid size-9 shrink-0 place-items-center text-[#94A3B8]"><MoreHorizontal /></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => toast('Post saved (demo)')}>Save post</DropdownMenuItem><DropdownMenuItem onSelect={() => onHide(post.id)}>Hide post</DropdownMenuItem><DropdownMenuItem onSelect={() => toast('Report received (demo)')}>Report post</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
    <div className="px-4 pb-4 text-sm leading-relaxed text-[#334155] sm:px-5">{post.id === 'amina' ? <><p>Thrilled to announce our Seed round is officially open on <span className="font-semibold text-[#3F4FA0]">Bridgeway</span>! 🚀</p><p className="mt-1">We are modernizing cold-chain logistics and agricultural telemetry for smallholder farmers across South Asia with real-time IoT and predictive harvest brokerage.</p><div className="mt-3 grid grid-cols-1 divide-y divide-[#DDE3FA] rounded-xl border border-[#DDE3FA] bg-[#F5F7FF] p-3 sm:grid-cols-2 sm:divide-x sm:divide-y-0"><div className="pb-2 sm:pb-0 sm:pr-3"><b className="block text-[10px] tracking-wide text-[#64748B]">ARR & MOMENTUM</b><span className="text-sm font-bold">$480K <span className="text-xs text-[#3F4FA0]">(3.2x YoY growth)</span></span></div><div className="pt-2 sm:pl-3 sm:pt-0"><b className="block text-[10px] tracking-wide text-[#64748B]">SEEKING ALLOCATION</b><span className="text-sm font-bold">$1.2M <span className="text-xs text-[#64748B]">(Lead investor committed: 40%)</span></span></div></div><p className="mt-3 text-xs text-[#64748B]">Verified deck, financial audit & KYC data room available for accredited investors and syndicate leads.</p></> : post.id === 'marcus' ? <><p>Meridian Ventures is deploying <b>$15M this quarter</b> into pre-Series A and Series A B2B infrastructure and cross-border settlement rails.</p><p className="mt-2 text-xs text-[#64748B]">{post.extra}</p><blockquote className="mt-3 rounded-r-xl border-l-4 border-[#3F4FA0] bg-[#F5F7FF] p-3 text-sm italic text-[#475569]">“We write initial checks of $750K – $2.5M with strong follow-on reserve capacity. Bilateral NDAs auto-counter-signed on initiation.”</blockquote></> : <p>{post.body}</p>}
      {post.tags.length > 0 && <div className="mt-3 flex flex-wrap gap-x-2 gap-y-1">{post.tags.map((tag) => <span key={tag} className="text-xs font-medium text-[#3F4FA0]">{tag}</span>)}</div>}
      {post.banner === 'deal' && <div className="relative mt-3 overflow-hidden rounded-xl bg-gradient-to-r from-[#14213D] to-[#293b7d] p-4 text-white sm:p-5"><div className="absolute -right-8 -top-16 size-48 rounded-full border-[4px] border-[#F5B544]/90" /><div className="relative flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><span className="rounded bg-[#F5B544] px-2 py-1 text-[9px] font-bold text-[#14213D]">AUDITED DEAL ROOM</span><span className="ml-2 text-xs font-semibold text-[#F5B544]">Confidential Data Vault</span><h3 className="mt-2 text-lg font-bold">AgriFlow Seed Deck · $1.2M Target</h3><p className="text-xs text-white/70">Telemetry hardware & freight escrow protocol</p></div><button disabled={requesting || requested} onClick={requestRoom} className="relative z-10 rounded-full border border-[#7586db] bg-[#3F4FA0]/70 px-4 py-2 text-xs font-semibold text-white disabled:opacity-80">{requesting ? 'Requesting…' : requested ? <><Check className="mr-1 inline size-4" />Requested</> : 'Request Deal Room →'}</button></div></div>}
      {post.banner === 'celebration' && <div className="mt-3 flex flex-col gap-3 rounded-xl bg-gradient-to-r from-[#F2705A] to-[#F5B544] p-4 text-white sm:flex-row sm:items-center sm:justify-between"><div><span className="rounded-full bg-[#14213D]/25 px-3 py-1 text-[9px] font-bold">ROUND OVERSUBSCRIBED</span><h3 className="mt-2 text-xl font-bold">MedScale Pre-Series A</h3><p className="text-xs">Syndicated across 6 regional angel groups</p></div><div className="rounded-xl bg-[#14213D] px-6 py-2 text-center sm:min-w-40"><span className="block text-[9px] text-white/70">CLOSED AMOUNT</span><b className="block text-lg text-[#F5B544]">$3.0M</b><span className="block text-sm font-bold text-[#F5B544]">Funded</span></div></div>}
    </div>
    <div className="flex flex-wrap items-center justify-between gap-2 border-t border-[#F1F3F6] px-4 py-2.5 text-[11px] text-[#64748B] sm:px-5"><span className="inline-flex items-center gap-1.5"><span className="grid size-5 place-items-center rounded-full bg-[#FEF3D8] text-[#d6a528]"><Star className="size-3 fill-current" /></span>{count + (liked ? 1 : 0)} {post.banner === 'celebration' ? 'congratulations' : post.id === 'marcus' ? 'venture partners & founders' : 'interested investors'}</span><span className="ml-auto">{comments.length + post.comments - 2} comments <span className="px-1.5">·</span><span className="font-semibold text-[#3F4FA0]">{post.banner === 'deal' ? '9 allocations requested' : post.kind === 'investor' ? '14 memos pitched' : '8 syndicated references'}</span></span></div>
    <div className="grid grid-cols-4 border-t border-[#F1F3F6] px-1 py-1">{[[post.banner === 'celebration' ? 'Congratulate' : 'Interested', ThumbsUp, () => setLiked((value) => !value), liked], ['Comment', MessageCircle, () => setCommentsOpen((value) => !value), commentsOpen], [post.kind === 'founder' ? 'Syndicate' : 'Share', post.kind === 'founder' ? Repeat2 : Share2, () => action(post.kind === 'founder' ? 'Syndicate' : 'Share'), false], [post.banner === 'deal' ? 'Send memo' : post.kind === 'investor' ? 'Pitch Memo' : 'Syndicate', post.banner === 'deal' ? Send : FileText, () => action(post.banner === 'deal' ? 'Send memo' : post.kind === 'investor' ? 'Pitch Memo' : 'Syndicate'), false]].map(([label, Icon, callback, active]) => { const ActionIcon = Icon as typeof Heart; const text = label as string; const invoke = callback as () => void; return <button key={text} onClick={invoke} aria-label={text} className={`flex min-h-10 min-w-0 items-center justify-center gap-1.5 text-[10px] font-semibold sm:text-xs ${active ? 'text-[#3F4FA0]' : 'text-[#64748B]'}`}><ActionIcon className="size-4 shrink-0" /><span className="hidden min-[380px]:inline truncate">{text}</span></button> })}</div>
    {commentsOpen && <div className="border-t border-[#F1F3F6] p-4"><div className="mb-3 flex gap-2"><input value={comment} onChange={(event) => setComment(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && comment.trim()) { setComments((items) => [...items, comment.trim()]); setComment('') } }} placeholder="Write a comment…" className="h-9 min-w-0 flex-1 rounded-full border border-[#E5E7EB] px-3 text-xs outline-none focus:ring-2 focus:ring-[#3F4FA0]" /><button onClick={() => { if (comment.trim()) { setComments((items) => [...items, comment.trim()]); setComment('') } }} className="rounded-full bg-[#EEF0FA] px-3 text-xs font-semibold text-[#3F4FA0]">Post</button></div>{comments.map((item, index) => <p key={`${item}-${index}`} className="mb-1 text-xs text-[#475569]"><b>{index < 2 ? ['Sarah J.', 'Omar K.'][index] : 'You'}:</b> {item}</p>)}</div>}
  </article>
}
