import { useEffect, useState } from 'react'
import { ChevronLeft, ChevronRight, Plus, X } from 'lucide-react'
import { toast } from 'sonner'
import { stories } from '../data'
import type { Story } from '../types'
import { Dialog, DialogContent, DialogTitle } from '@/components/ui/dialog'

export function SuccessStories({ initials, onShare }: { initials: string; onShare: () => void }) {
  const [hidden, setHidden] = useState(() => localStorage.getItem('bridgeway-stories-hidden') === 'true')
  const [story, setStory] = useState<Story | null>(null)
  const [index, setIndex] = useState(0)
  useEffect(() => { localStorage.setItem('bridgeway-stories-hidden', String(hidden)) }, [hidden])
  useEffect(() => { if (!story) return; const timer = window.setInterval(() => setIndex((value) => value >= 3 ? 0 : value + 1), 5000); return () => window.clearInterval(timer) }, [story])
  const move = (direction: number) => setStory(stories[(stories.findIndex((item) => item.id === story?.id) + direction + stories.length) % stories.length] ?? null)
  return <>
    <section className="rounded-2xl border border-[#E5E7EB] bg-white p-4 shadow-[0_3px_14px_rgba(20,33,61,0.06)] sm:p-5" aria-label="Success stories">
      <div className="mb-4 flex items-center gap-2"><h2 className="text-sm font-bold">Success Stories</h2><span className="hidden text-[11px] text-[#64748B] sm:inline">· Deals closed on Bridgeway</span><button className="ml-auto text-xs font-semibold text-[#3F4FA0]" onClick={() => setHidden((value) => !value)}>{hidden ? 'Show stories' : 'Hide stories'}</button><button onClick={() => setIndex((value) => Math.max(0, value - 1))} aria-label="Previous stories" className="grid size-8 place-items-center rounded-full border border-[#E5E7EB] text-[#64748B] hover:bg-[#F3F4F6]"><ChevronLeft className="size-4" /></button><button onClick={() => setIndex((value) => value + 1)} aria-label="Next stories" className="grid size-8 place-items-center rounded-full border border-[#E5E7EB] text-[#64748B] hover:bg-[#F3F4F6]"><ChevronRight className="size-4" /></button></div>
      {!hidden && <div className="flex snap-x gap-3 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
        <button onClick={onShare} className="flex h-[200px] w-[128px] shrink-0 snap-start flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[#B8C2E2] bg-[#F8FAFC] px-3 text-center"><span className="mb-5 grid size-8 place-items-center rounded-full bg-[#3F4FA0] text-xs font-bold text-white">{initials}</span><span className="grid size-9 place-items-center rounded-full bg-[#3F4FA0] text-white"><Plus /></span><span className="mt-1 text-xs font-bold">Share Deal Close</span><span className="mt-auto text-[10px] text-[#64748B]">Post Syndicate Win</span></button>
        {stories.map((item) => <button key={item.id} onClick={() => { setStory(item); setIndex(0) }} className="group relative flex h-[200px] w-[128px] shrink-0 snap-start flex-col justify-between overflow-hidden rounded-2xl p-3 text-left text-white transition-transform hover:scale-[1.02]" style={{ background: item.gradient }}><span className="flex items-start justify-between"><span className="grid size-8 place-items-center rounded-full border-2 border-white/80 bg-[#14213D] text-[10px] font-bold">{item.initials}</span><span className="rounded-full bg-black/35 px-2 py-1 text-[9px] font-semibold">{item.chip}</span></span><span><span className="block text-[10px] text-white/80">{item.name}</span><span className="block text-xs font-bold leading-snug">{item.headline}</span></span></button>)}
      </div>}
    </section>
    <Dialog open={!!story} onOpenChange={(open) => { if (!open) { setStory(null); setIndex(0) } }}><DialogContent className="max-w-[420px] overflow-hidden rounded-2xl border-0 bg-[#14213D] p-0 text-white sm:rounded-2xl"><DialogTitle className="sr-only">Success story</DialogTitle>{story && <div className="relative flex min-h-[560px] flex-col justify-between p-5" style={{ background: story.gradient }}><div className="flex gap-1">{stories.map((item, i) => <span key={item.id} className="h-1 flex-1 rounded bg-white/40"><span className={`block h-full rounded bg-white ${i < index ? 'w-full' : i === index ? 'w-1/2' : 'w-0'}`} /></span>)}</div><button onClick={() => setStory(null)} className="absolute right-4 top-8 rounded-full bg-black/20 p-2" aria-label="Close story"><X className="size-4" /></button><div className="mt-4 flex items-center gap-2"><span className="grid size-10 place-items-center rounded-full border-2 border-white bg-[#14213D] text-sm font-bold">{story.initials}</span><span className="font-semibold">{story.name}</span></div><button className="absolute inset-x-0 top-1/3 h-1/3" aria-label="Next story" onClick={() => move(1)} /><div className="relative z-10"><p className="mb-4 text-3xl font-bold">{story.headline}</p><button onClick={() => toast('Congratulations sent (demo)')} className="w-full rounded-xl bg-[#F5B544] px-4 py-3 font-bold text-[#14213D]">Congratulate</button><div className="mt-3 flex justify-between"><button onClick={() => move(-1)} className="rounded-lg bg-black/20 px-3 py-2 text-sm">Previous</button><button onClick={() => move(1)} className="rounded-lg bg-black/20 px-3 py-2 text-sm">Next</button></div></div></div>}</DialogContent></Dialog>
  </>
}
