import type { Celebration, Invitation, NetworkEvent, NetworkPage, Person } from './types'

const gradients = ['from-[#d9cdec] to-[#e8e4f1]', 'from-[#cfe2f4] to-[#e2ebf8]', 'from-[#f9ded8] to-[#e8dff5]', 'from-[#f8e9bd] to-[#dce6f5]', 'from-[#e4d8ef] to-[#f8dfdf]']
export const invitations: Invitation[] = [
  { id:'i1',name:'Aamina Sheikh',initials:'AS',role:'Founder',headline:'Founder & CEO @ AgriMatrix · Building cold-chain IoT hardware',sector:'AgriTech',mutuals:87,location:'Lahore',gradient:gradients[0],match:'Invests in AgriTech · Ticket size fits ($500K–$1M)',mutualName:'Hassan Sardar' },
  { id:'i2',name:'Taimur Chaudhry',initials:'TC',role:'Investor',headline:'Managing Partner @ Indus Horizon Capital · Seed to Series A syndicate lead',sector:'Venture Capital',mutuals:42,location:'Lahore',gradient:gradients[1],match:'Co-syndicated 2 deals with Meridian Ventures',mutualName:'Zainab Bilal' },
  { id:'i3',name:'Dr. Rabia Mansoor',initials:'DR',role:'Founder',headline:'Co-Founder @ PulsoHealth · AI triage clinical copilot platform',sector:'HealthTech',mutuals:19,location:'Karachi',gradient:gradients[2],match:'Looking for Syndicate Lead in HealthTech',mutualName:'Bilal & Co' },
  { id:'i4',name:'Sana Malik',initials:'SM',role:'Founder',headline:'Building climate-smart supply chains for growing farms',sector:'AgriTech',mutuals:31,location:'Lahore',gradient:gradients[3],match:'Shared interest in resilient food systems',mutualName:'Omar Rasheed' },
  { id:'i5',name:'Faraz Ahmed',initials:'FA',role:'Investor',headline:'Angel investor backing early-stage fintech teams',sector:'FinTech',mutuals:24,location:'Islamabad',gradient:gradients[4],match:'Active in your preferred seed stage',mutualName:'Mariam Zaidi' },
  { id:'i6',name:'Hira Qureshi',initials:'HQ',role:'Founder',headline:'Founder @ MedRoute · Making care more accessible',sector:'HealthTech',mutuals:15,location:'Karachi',gradient:gradients[0],match:'Both connected to HealthTech founders',mutualName:'Sarah Jenkins' },
]
export const celebrations: Celebration[] = [
  {id:'c1',initials:'ZA',name:'Zoya Alvi',text:'closed an oversubscribed $850K Angel round for SolarGrid Energy',time:'3 hours ago',sector:'CleanTech',kind:'deal'},
  {id:'c2',initials:'BA',name:'Bilal Ahmad',text:'was appointed Managing Director at Indus Valley Syndicate',time:'1 day ago',sector:'Career Move',kind:'career'},
  {id:'c3',initials:'SJ',name:'Sarah Jenkins',text:'published new syndicated investment mandate for Q3 2026',time:'2 days ago',sector:'Deal Mandate',kind:'mandate'},
  {id:'c4',initials:'MK',name:'Mariam Khan',text:'joined the advisory board at Crescent Moon Ventures',time:'3 days ago',sector:'Career Move',kind:'career'},
  {id:'c5',initials:'AR',name:'Adil Rehman',text:'secured a new strategic partnership for TerraFoods',time:'4 days ago',sector:'AgriTech',kind:'deal'},
  {id:'c6',initials:'NZ',name:'Noor Zaman',text:'announced a new investment mandate focused on logistics',time:'1 week ago',sector:'Deal Mandate',kind:'mandate'},
]
export const connections: Person[] = [
  {id:'p1',name:'Ali Khawar',initials:'AK',role:'Investor',headline:'Partner @ Fatima Gobi Ventures',sector:'FinTech',mutuals:21,location:'Lahore',gradient:gradients[0],connected:'2d ago'},
  {id:'p2',name:'Mariam Zaidi',initials:'MZ',role:'Founder',headline:'Founder @ Medivolt Health',sector:'HealthTech',mutuals:17,location:'Karachi',gradient:gradients[1],connected:'1w ago'},
  {id:'p3',name:'Omar Rasheed',initials:'OR',role:'Investor',headline:'Angel Investor & Syndicate Lead',sector:'Venture Capital',mutuals:34,location:'Lahore',gradient:gradients[2],connected:'2w ago'},
  ...['Ayesha Iqbal','Hamid Raza','Naveed Shah','Saira Noor','Jamal Abbas','Kiran Tariq','Faisal Khan','Mina Aslam','Daniyal Haq'].map((name,i)=>({id:`p${i+4}`,name,initials:name.split(' ').map(n=>n[0]).join(''),role:(i%2?'Founder':'Investor') as Person['role'],headline:['Managing Partner @ Crescent Moon','Founder building payment infrastructure','Early-stage investor in B2B teams'][i%3],sector:['AgriTech','FinTech','Logistics'][i%3],mutuals:12+i*3,location:i%2?'Lahore':'Islamabad',gradient:gradients[i%gradients.length],connected:`${i+3}w ago`}))
]
const suggestedRows: [string,string,string,string,string,number,string][] = [
 ['Syed Asad','SA','Investor','Lead Partner @ Karakoram Angels · Early-stage B2B','FinTech · GCC',14,'Lahore'],['Nida Karim','NK','Founder','Building B2B payment rails for GCC-Pak corridor','Payments · Cross-border',26,'Karachi'],['Farhan Tareen','FT','Investor','Venture Partner @ Crescent Moon · Health & BioTech','HealthTech · Series A',38,'Lahore'],['Mahnoor Khan','MK','Founder','CTO & Co-Founder @ LogiFleet AI · Autonomous','Logistics · AI',9,'Islamabad'],['Usman Rafiq','UR','Founder','CEO @ Faisalabad Textile Tech · LUMS Alum','Supply Chain · IoT',51,'Lahore'],['Shanzeh Zia','SZ','Investor','Chair @ Lahore Angel Syndicate · Builder-led','Angel · Seed',68,'Lahore'],['Haris Hashmi','HH','Founder','Founder @ Agronix Labs · NIC Lahore Alum','AgriTech · Drones',33,'Lahore'],['Mirza Baig','MB','Investor','General Partner @ Ravi Capital Partners','Growth · FinTech',12,'Karachi'],['Zainab Malik','ZM','Investor','Principal @ Highline Capital · SaaS & DevTools','Enterprise · Series A',44,'Lahore'],['Dr. Tariq Aziz','TA','Founder','CEO @ NanoHealth Genomics · Precision care','BioTech · DeepTech',19,'Islamabad'],['Ayla Farooq','AF','Investor','Angel Syndicate Scout · Female founders network','Early Stage · Consumer',62,'Lahore'],['Hamza Shah','HS','Founder','Co-Founder @ SolarIQ · Distributed micro-grid AI','CleanTech · Infra',27,'Karachi'],['Raza Siddiqui','RS','Investor','Partner @ Frontier Growth Fund','FinTech · Series B',21,'Lahore'],['Maha Ahmed','MA','Founder','Building farm-to-market tools for growers','AgriTech · SaaS',18,'Lahore'],['Sami Rehman','SR','Investor','Backing founders across emerging markets','FinTech · Seed',30,'Islamabad'],['Iqra Javed','IJ','Founder','Founder @ GreenBasket marketplace','AgriTech · Commerce',16,'Lahore'],['Dawood Ali','DA','Investor','Venture Partner focused on digital health','HealthTech · Seed',25,'Karachi'],['Sana Ilyas','SI','Founder','Cross-border payments for SMEs','FinTech · Payments',39,'Lahore'],['Bilal Rauf','BR','Investor','Angel investor and operator','Logistics · Series A',13,'Multan'],['Hania Noor','HN','Founder','Affordable diagnostics for regional clinics','HealthTech · AI',29,'Lahore'],['Usama Mir','UM','Investor','Principal at Indus Horizon Capital','AgriTech · Seed',22,'Lahore'],['Mishal Ahmed','MA','Founder','Climate analytics for food supply chains','AgriTech · Climate',37,'Faisalabad'],['Kashif Nadeem','KN','Investor','Investor in B2B software and fintech','FinTech · SaaS',11,'Lahore'],['Areeba Khan','AK','Founder','Smart irrigation and crop monitoring','AgriTech · IoT',32,'Lahore'],
]
export const people: Person[] = suggestedRows.map((row,i)=>({id:`s${i+1}`,name:row[0],initials:row[1],role:row[2] as Person['role'],headline:row[3],sector:row[4],mutuals:row[5],location:row[6],gradient:gradients[i%gradients.length]}))
export const events: NetworkEvent[] = [{id:'e1',month:'OCT',day:'18',title:'Bridgeway Founder & Investor Mixer',organizer:'Bridgeway Network',place:'Online'},{id:'e2',month:'OCT',day:'24',title:'AgriTech Capital Forum',organizer:'Pakistan AgriTech Council',place:'Lahore, Pakistan'},{id:'e3',month:'NOV',day:'02',title:'FinTech Syndicate Roundtable',organizer:'Meridian Ventures',place:'Online'}]
export const pages: NetworkPage[] = [{id:'pg1',initials:'BW',name:'Bridgeway Network',description:'Connections, capital and collaboration.'},{id:'pg2',initials:'MA',name:'Meridian Ventures',description:'Backing bold founders across the region.'},{id:'pg3',initials:'PA',name:'Pakistan AgriTech',description:'Building a stronger agricultural future.'},{id:'pg4',initials:'CA',name:'Crescent Moon Angels',description:'Early-stage founders and angel investors.'}]
