import { useEffect, useMemo, useState } from 'react'
import { useInView } from 'react-intersection-observer'
import { AnimatePresence, motion, useReducedMotion } from 'motion/react'
import { Check, Clock3, FileText, MoreVertical, PartyPopper, Search, Users, X } from 'lucide-react'
import { toast } from 'sonner'
import { useNavigate } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Avatar } from '@/components/common/Avatar'
import type { AvatarTone } from '@/components/common/Avatar'
import { CoverStrip } from '@/components/common/CoverStrip'
import { EmptyState } from '@/components/common/EmptyState'
import { RoleChip } from '@/components/common/RoleChip'
import { SectionHeader } from '@/components/common/SectionHeader'
import { celebrations, events, pages } from '../data'
import type { Celebration, Invitation, NetworkEvent, NetworkPage, Person } from '../types'

const panel = 'min-w-0 rounded-2xl border border-[#E5E7EB] bg-white p-4 shadow-[0_1px_2px_rgba(16,24,40,0.04),0_6px_20px_rgba(16,24,40,0.05)] sm:p-6'
const tones: AvatarTone[] = ['violet','indigo','coral','sky','amber','amber-tint','indigo-tint','navy']
function toneFor(id: string): AvatarTone { const index=Number(id.match(/\d+$/)?.[0]??1)-1;if(id==='p1')return 'indigo';if(id==='p2')return 'amber-tint';if(id==='p3')return 'violet';return id.startsWith('i')?(['violet','indigo','coral','sky','amber','navy'] as AvatarTone[])[index]??'indigo':tones[index%tones.length] }
function coverFor(id: string): 'lavender'|'sky'|'peach'|'coral'|'cream'|'lilac' { return (['lavender','sky','peach','coral','cream','lilac'] as const)[(Number(id.match(/\d+$/)?.[0]??1)-1)%6] }

export function InvitationSection({items,focused,onAccept,onIgnore,onUndo}:{items:Invitation[];focused?:boolean;onAccept:(item:Invitation)=>void;onIgnore:(item:Invitation)=>void;onUndo?:()=>void}) {
  const shown=focused?items:items.slice(0,3);const count=items.length+8
  return <section aria-labelledby="invitations-title" className={panel}><SectionHeader id="invitations-title" title="Invitations" badge={<span aria-live="polite" className="rounded-full bg-[#FDE9E5] px-2.5 py-1 text-[11px] font-bold text-[#C2412D]">{count} new</span>} action={!focused&&<a href="?tab=invitations" className="shrink-0 pt-1 text-xs font-bold text-[#3F4FA0]">Show all ({count}) →</a>}/>{items.length===0?<EmptyState text="No pending invitations"/>:<div className="grid min-w-0 grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3"><AnimatePresence mode="popLayout">{shown.map(item=><InvitationCard key={item.id} item={item} onAccept={onAccept} onIgnore={onIgnore} onUndo={onUndo}/>)}</AnimatePresence></div>}</section>
}

function InvitationCard({item,onAccept,onIgnore,onUndo}:{item:Invitation;onAccept:(item:Invitation)=>void;onIgnore:(item:Invitation)=>void;onUndo?:()=>void}) {
  const [busy,setBusy]=useState(false); const reduced=useReducedMotion()
  async function accept(){setBusy(true);await new Promise(resolve=>setTimeout(resolve,600));onAccept(item);toast(`You are now connected with ${item.name}`)}
  function ignore(){onIgnore(item);toast('Invitation ignored',{action:{label:'Undo',onClick:()=>onUndo?.()}})}
  return <motion.article layout initial={reduced?false:{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,height:0,scale:.97}} whileHover={reduced?undefined:{y:-2}} className="min-w-0 overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white shadow-sm transition-shadow hover:shadow-md">
    <div className="relative"><CoverStrip variant={coverFor(item.id)} height={64}/><div className="absolute -bottom-7 left-4 rounded-full ring-[3px] ring-white"><Avatar name={item.name} size={56} tone={toneFor(item.id)} verified/></div></div>
    <div className="p-4 pt-2"><div className="flex h-8 justify-end"><RoleChip role={item.role}/></div><h3 className="truncate text-base font-semibold text-[#14213D]">{item.name}</h3><p className="mt-1 line-clamp-2 min-h-9 text-xs leading-[18px] text-[#475569]">{item.headline}</p>
      <div className="mt-3 flex min-h-12 items-start gap-2 rounded-xl border border-[#E5E7EB] bg-[#FAFAF8] p-2.5 text-xs leading-4 text-[#475569]"><span className="text-base font-bold text-[#3F4FA0]">✧</span><span className="line-clamp-2">{item.match}</span></div>
      <div className="my-3 flex min-w-0 items-center gap-2 text-xs text-[#64748B]"><span className="flex shrink-0 -space-x-2"><Avatar name={item.mutualName} size={24} tone="sky"/><Avatar name="Mariam Zaidi" size={24} tone="amber"/><Avatar name="Bilal Khan" size={24} tone="violet"/></span><span className="truncate">{item.mutualName} + {item.mutuals} mutuals</span></div>
      <div className="grid grid-cols-2 gap-3"><Button variant="outline" className="h-10 whitespace-nowrap" onClick={ignore}>Ignore</Button><Button disabled={busy} onClick={accept} className="h-10 whitespace-nowrap bg-[#F5B544] font-semibold text-[#14213D] hover:bg-[#e9a932]">{busy?'Accepting…':'Accept'}</Button></div>
    </div>
  </motion.article>
}

export function CelebrationSection({focused}:{focused?:boolean}) {
  const [done,setDone]=useState<string[]>([]);const [hello,setHello]=useState<Celebration|null>(null);const shown=focused?celebrations:celebrations.slice(0,3)
  return <section aria-labelledby="celebrations-title" className={panel}><SectionHeader id="celebrations-title" title="Celebrations" subtitle="Stay close to deal momentum and team transitions" badge={<span className="shrink-0 rounded-full bg-[#FEF3D8] px-2.5 py-1 text-[11px] font-bold text-[#8A5A00]">{shown.length} updates</span>}/><div className="space-y-3">{shown.map(item=><CelebrationRow key={item.id} item={item} done={done.includes(item.id)} onCongrats={()=>{setDone(value=>[...value,item.id]);toast('Congratulations sent (demo)')}} onHello={()=>setHello(item)}/>)}</div><SayHelloDialog key={hello?.id??'closed'} item={hello} onClose={()=>setHello(null)}/></section>
}

function CelebrationRow({item,done,onCongrats,onHello}:{item:Celebration;done:boolean;onCongrats:()=>void;onHello:()=>void}) {
  const TypeIcon=item.kind==='deal'?Check:item.kind==='career'?Users:FileText
  return <article className="flex min-w-0 flex-wrap items-center gap-3 rounded-xl border border-[#E5E7EB] bg-[#FAFAF8] p-3 sm:flex-nowrap"><span className="relative grid size-12 shrink-0 place-items-center rounded-full bg-[#EEF0FA] text-xs font-bold text-[#3F4FA0]">{item.initials}<i className="absolute -bottom-0.5 -right-0.5 grid size-[18px] place-items-center rounded-full border-2 border-white bg-[#F5B544] text-[#14213D]"><TypeIcon className="size-2.5"/></i></span><div className="min-w-0 flex-1"><p className="line-clamp-2 text-xs leading-5 text-[#14213D]"><strong>{item.name}</strong> {item.text}</p><p className="mt-0.5 text-[11px] text-[#94A3B8]">{item.time} · {item.sector}</p></div><div className="w-full sm:w-auto">{item.kind==='deal'?<Button variant="outline" disabled={done} onClick={onCongrats} className="h-10 w-full whitespace-nowrap border-[#F5B544] text-[#8A5A00] sm:w-auto">{done?'Congratulated ✓':<>Congratulate <PartyPopper className="ml-1 size-4"/></>}</Button>:item.kind==='career'?<Button variant="outline" onClick={onHello} className="h-10 w-full whitespace-nowrap border-[#3F4FA0]/50 text-[#3F4FA0] sm:w-auto">Say hello</Button>:<Button variant="outline" onClick={()=>toast('Mandates are coming soon (demo)')} className="h-10 w-full whitespace-nowrap border-[#14213D]/40 text-[#14213D] sm:w-auto">Read mandate</Button>}</div></article>
}
function SayHelloDialog({item,onClose}:{item:Celebration|null;onClose:()=>void}) { const initial=item?`Hi ${item.name.split(' ')[0]}, congratulations on the new role!`:'';const [message,setMessage]=useState(initial);return <Dialog open={!!item} onOpenChange={open=>!open&&onClose()}><DialogContent><DialogHeader><DialogTitle>Say hello to {item?.name}</DialogTitle></DialogHeader><textarea value={message||initial} onChange={event=>setMessage(event.target.value)} className="min-h-24 w-full rounded-md border border-[#E5E7EB] p-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#3F4FA0]"/><DialogFooter><Button className="bg-[#F5B544] text-[#14213D] hover:bg-[#e9a932]" onClick={()=>{toast('Message sent (demo)');onClose()}}>Send</Button></DialogFooter></DialogContent></Dialog> }

export function ConnectionsSection({items,onRemove,focused}:{items:Person[];onRemove:(person:Person)=>void;focused?:boolean}) {
  const [filter,setFilter]=useState('All');const [sort,setSort]=useState('recent');const [query,setQuery]=useState('');const [limit,setLimit]=useState(focused?9:3);const [target,setTarget]=useState<Person|null>(null);const navigate=useNavigate()
  const filtered=useMemo(()=>items.filter(person=>(filter==='All'||person.role===filter.slice(0,-1))&&`${person.name} ${person.headline}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='sector'?a.sector.localeCompare(b.sector):0),[items,filter,sort,query])
  const shown=filtered.slice(0,limit);const total=1505+items.length-12
  return <section aria-labelledby="connections-title" className={panel}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><SectionHeader id="connections-title" title="All connections" badge={<span aria-live="polite" className="rounded-full bg-[#FEF3D8] px-2.5 py-1 text-[11px] font-bold text-[#8A5A00]">{total.toLocaleString()} connections</span>} subtitle="People you're connected with on Bridgeway."/></div><div className="flex items-center gap-2 text-xs text-[#64748B]">Sort by:<Select value={sort} onValueChange={setSort}><SelectTrigger className="h-9 w-36"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="recent">Recently added</SelectItem><SelectItem value="name">Name</SelectItem><SelectItem value="sector">Sector</SelectItem></SelectContent></Select></div></div>
    {focused&&<div className="relative mb-3"><Search className="absolute left-3 top-2.5 size-4 text-[#94A3B8]"/><Input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search your network" className="pl-9"/></div>}
    <div className="my-3 flex gap-2 overflow-x-auto pb-1">{['All','Investors','Founders'].map(chip=><button key={chip} onClick={()=>setFilter(chip)} className={`shrink-0 whitespace-nowrap rounded-full border px-3 py-1.5 text-[11px] font-semibold ${filter===chip?'border-[#14213D] bg-[#14213D] text-white':'border-[#E5E7EB] bg-[#F3F4F6] text-[#64748B]'}`}>{chip} ({chip==='All'?total:chip==='Investors'?612+items.filter(person=>person.role==='Investor').length-5:893+items.filter(person=>person.role==='Founder').length-7})</button>)}</div>
    <div className="grid min-w-0 grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3"><AnimatePresence mode="popLayout">{shown.map(person=><ConnectionCard key={person.id} person={person} onMessage={()=>navigate('/communications')} onRemove={()=>setTarget(person)}/>)}</AnimatePresence></div>
    {focused&&filtered.length>limit&&<Button variant="outline" className="mt-4 h-10 w-full" onClick={()=>setLimit(value=>value+9)}>Load more</Button>}{!shown.length&&<EmptyState text="No connections match your search."/>}
    {!focused&&<a href="?tab=all" className="mt-4 block text-center text-xs font-semibold text-[#3F4FA0]">View all connections →</a>}
    <Dialog open={!!target} onOpenChange={open=>!open&&setTarget(null)}><DialogContent><DialogHeader><DialogTitle>Remove {target?.name} from your connections?</DialogTitle></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setTarget(null)}>Cancel</Button><Button className="bg-[#F2705A] text-white hover:bg-[#dc5e4a]" onClick={()=>{if(target)onRemove(target);setTarget(null)}}>Remove</Button></DialogFooter></DialogContent></Dialog>
  </section>
}

function ConnectionCard({person,onMessage,onRemove}:{person:Person;onMessage:()=>void;onRemove:()=>void}) { return <motion.article layout initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,height:0}} className="min-w-0 rounded-2xl border border-[#E5E7EB] bg-white p-4 shadow-sm"><div className="flex min-w-0 items-center gap-3"><Avatar name={person.name} size={48} tone={toneFor(person.id)} verified/><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{person.name}</h3><RoleChip role={person.role}/><p className="truncate text-xs text-[#94A3B8]">{person.headline}</p></div></div><div className="mt-3 flex min-w-0 items-center gap-2 border-t border-[#E5E7EB] pt-3 text-[11px] text-[#94A3B8]"><span className="mr-auto truncate">Connected {person.connected}</span><Button className="h-8 whitespace-nowrap bg-[#F5B544] px-3 text-[11px] text-[#14213D] hover:bg-[#e9a932]" onClick={onMessage}>Message</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="size-8 shrink-0" aria-label={`More options for ${person.name}`}><MoreVertical className="size-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>toast('Profiles are coming soon (demo)')}>View profile</DropdownMenuItem><DropdownMenuItem onSelect={onRemove} className="text-[#F2705A]">Remove connection</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></motion.article> }

export function PeopleSection({items,pending,onTogglePending,onDismiss}:{items:Person[];pending:string[];onTogglePending:(id:string)=>void;onDismiss:(id:string)=>void;focused?:boolean}) {
  const [filter,setFilter]=useState('All');const [visible,setVisible]=useState(12);const [loading,setLoading]=useState(false);const {ref,inView}=useInView({rootMargin:'260px'});const reduced=useReducedMotion()
  const filtered=items.filter(person=>filter==='All'||filter==='Investor'||filter==='Founder'?filter==='All'||person.role===filter:filter==='From Lahore'?person.location==='Lahore':person.sector.toLowerCase().includes('agritech')||person.sector.toLowerCase().includes('fintech'))
  useEffect(()=>{if(!inView||loading||visible>=filtered.length)return;const start=setTimeout(()=>{setLoading(true);setTimeout(()=>{setVisible(count=>Math.min(count+8,filtered.length));setLoading(false)},700)},0);return()=>clearTimeout(start)},[inView,loading,visible,filtered.length])
  return <section aria-labelledby="people-title" className={panel}><SectionHeader id="people-title" title="People you may know" subtitle="Suggestions based on your sector and location." action={<a href="?tab=familiar" className="shrink-0 pt-1 text-xs font-bold text-[#3F4FA0]">Show all →</a>}/><div className="mb-4 flex gap-2 overflow-x-auto pb-1">{['All','Investor','Founder','From Lahore','AgriTech & FinTech'].map(chip=><button key={chip} onClick={()=>setFilter(chip)} className={`shrink-0 whitespace-nowrap rounded-full border px-3 py-1.5 text-[11px] ${filter===chip?'border-[#14213D] bg-[#14213D] text-white':'border-[#E5E7EB] text-[#64748B]'}`}>{chip}</button>)}</div><div className="grid min-w-0 grid-cols-2 gap-3 sm:gap-4 md:grid-cols-3 xl:grid-cols-4"><AnimatePresence mode="popLayout">{filtered.slice(0,visible).map((person,index)=><PersonCard key={person.id} person={person} pending={pending.includes(person.id)} onToggle={()=>onTogglePending(person.id)} onDismiss={()=>onDismiss(person.id)} index={index} reduced={!!reduced}/>)}</AnimatePresence></div>{loading&&<div className="pt-4"><p className="mb-3 text-center text-xs text-[#94A3B8]">Loading more people…</p><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[0,1,2,3].map(key=><div key={key} className="h-32 animate-pulse rounded-xl border border-[#E5E7EB] bg-[#F3F4F6]"/>)}</div></div>}<div ref={ref} className="h-2"/>{visible>=filtered.length&&<p className="pt-3 text-center text-xs text-[#94A3B8]">You're all caught up</p>}</section>
}

function PersonCard({person,pending,onToggle,onDismiss,index,reduced}:{person:Person;pending:boolean;onToggle:()=>void;onDismiss:()=>void;index:number;reduced:boolean}) { return <motion.article layout initial={reduced?false:{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,height:0}} transition={{delay:Math.min(index%12,8)*.06}} whileHover={reduced?undefined:{y:-2}} className="relative min-w-0 overflow-hidden rounded-2xl border border-[#E5E7EB] bg-white pb-3 text-center shadow-sm"><CoverStrip variant={coverFor(person.id)} height={56}/><button onClick={onDismiss} className="absolute right-2 top-2 grid size-7 place-items-center rounded-full bg-[#14213D]/35 text-white" aria-label={`Dismiss ${person.name}`}><X className="size-4"/></button><div className="-mt-8 flex justify-center"><Avatar name={person.name} size={64} tone={toneFor(person.id)} verified/></div><div className="px-3"><h3 className="mt-1 truncate text-sm font-semibold">{person.name}</h3><RoleChip role={person.role}/><p className="mt-1 line-clamp-2 min-h-9 text-xs leading-4 text-[#64748B]">{person.headline}</p><span className="mx-auto mt-1 block w-fit max-w-full truncate rounded-md bg-[#F3F4F6] px-2 py-1 text-[10px] text-[#64748B]">{person.sector}</span><p className="my-2 flex items-center justify-center gap-1 text-[10px] text-[#94A3B8]"><Users className="size-3"/>{person.mutuals} mutuals</p><Button variant="outline" onClick={()=>{onToggle();toast(pending?'Request cancelled (demo)':'Connection request sent (demo)')}} className={`h-10 w-full rounded-xl text-xs ${pending?'bg-[#F3F4F6] text-[#64748B]':'border-[#3F4FA0] text-[#3F4FA0]'}`}>{pending?<><Clock3 className="size-4"/>Pending</>:'+ Connect'}</Button></div></motion.article> }

export function EventsView(){const [attending,setAttending]=useState<string[]>([]);return <section aria-labelledby="events-title" className={panel}><SectionHeader id="events-title" title="Events" subtitle="Meet people building the Bridgeway network."/>{events.length?events.map(event=><EventRow key={event.id} event={event} attending={attending.includes(event.id)} onToggle={()=>setAttending(value=>value.includes(event.id)?value.filter(id=>id!==event.id):[...value,event.id])}/>):<EmptyState text="No upcoming events yet"/>}</section>}
function EventRow({event,attending,onToggle}:{event:NetworkEvent;attending:boolean;onToggle:()=>void}){return <article className="mb-3 flex min-w-0 items-center gap-3 rounded-xl border border-[#E5E7EB] p-3"><div className="grid size-14 shrink-0 place-items-center rounded-lg bg-[#FEF3D8] text-center"><span className="text-[10px] font-bold text-[#8A5A00]">{event.month}</span><strong className="text-lg">{event.day}</strong></div><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{event.title}</h3><p className="truncate text-xs text-[#64748B]">{event.organizer} · {event.place}</p></div><Button variant="outline" onClick={onToggle} className="whitespace-nowrap">{attending?'Attending':'Attend'}</Button></article>}

export function PagesView(){const [followed,setFollowed]=useState(pages.map(page=>page.id));const toggle=(id:string)=>setFollowed(value=>value.includes(id)?value.filter(item=>item!==id):[...value,id]);return <section aria-labelledby="pages-title" className={panel}><SectionHeader id="pages-title" title="Pages" subtitle="Organizations and communities you follow."/>{followed.length===0&&<EmptyState text="You're not following any pages yet"/>}<div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{pages.map(page=><PageRow key={page.id} page={page} following={followed.includes(page.id)} onToggle={()=>toggle(page.id)}/>)}</div></section>}
function PageRow({page,following,onToggle}:{page:NetworkPage;following:boolean;onToggle:()=>void}){return <article className="flex min-w-0 items-center gap-3 rounded-xl border border-[#E5E7EB] p-3"><div className="grid size-12 shrink-0 place-items-center rounded-xl bg-[#EEF0FA] font-bold text-[#3F4FA0]">{page.initials}</div><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{page.name}</h3><p className="truncate text-xs text-[#64748B]">{page.description}</p></div><Button variant="outline" onClick={onToggle} className="whitespace-nowrap">{following?'Following':'Follow'}</Button></article>}


