import type { NotificationData } from "./types";

export const INITIAL_NOTIFICATIONS: NotificationData[] = [
  {
    id: "n1",
    group: "Today",
    kind: "connection_request",
    category: "Connections",
    timeAgo: "25m ago",
    unread: true,
    avatarName: "Aamina Sheikh",
    actorName: "Aamina Sheikh",
    role: "Founder",
    verified: true,
    message: "sent you a connection request",
    actions: ["accept", "ignore"],
    tone: { background: "#7C5CBF", color: "#FFFFFF" },
  },
  {
    id: "n2",
    group: "Today",
    kind: "opportunity_interest",
    category: "Opportunities",
    timeAgo: "1h ago",
    unread: true,
    avatarName: "Apex Capital Syndicate",
    actorName: "Apex Capital Syndicate",
    role: "Investor",
    verified: true,
    message: "expressed interest in AgriFlow Seed Round",
    highlight: "AgriFlow Seed Round",
    actions: ["view"],
    shape: "square",
    tone: { background: "#14213D", color: "#F5B544" },
  },
  {
    id: "n3",
    group: "Today",
    kind: "message",
    category: "Messages",
    timeAgo: "2h ago",
    unread: true,
    avatarName: "Nida Karim",
    actorName: "Nida Karim",
    role: "Founder",
    message: "sent you a message:",
    quote: "Syndicate lead agreement attached for your review.",
    actions: ["reply"],
    tone: { background: "#5BA4E6", color: "#FFFFFF" },
  },
  {
    id: "n4",
    group: "Today",
    kind: "connection_accepted",
    category: "Connections",
    timeAgo: "4h ago",
    unread: false,
    avatarName: "Taimur Chaudhry",
    actorName: "Taimur Chaudhry",
    role: "Investor",
    message: "accepted your connection request",
    statusText: "You are now connected",
    actions: ["message"],
    tone: { background: "#14213D", color: "#FFFFFF" },
  },
  {
    id: "n5",
    group: "This week",
    kind: "introduction",
    category: "Brokered Introductions",
    timeAgo: "1d ago",
    unread: true,
    avatarName: "Bridgeway",
    actorName: "Bridgeway",
    role: "Broker",
    message: "has introduced you to Indus Horizon Capital after mutual mandate alignment",
    highlight: "Indus Horizon Capital",
    actions: ["say_hello"],
  },
  {
    id: "n6",
    group: "This week",
    kind: "match",
    category: "Opportunities",
    timeAgo: "2d ago",
    unread: true,
    avatarName: "Karakoram Angels",
    lead: "New match: Karakoram Angels",
    message: "is looking for early-stage FinTech & AgriTech raises (PKR 15M – 45M)",
    actions: ["view_opportunity"],
  },
  {
    id: "n7",
    group: "This week",
    kind: "milestone",
    category: "Milestones",
    timeAgo: "3d ago",
    unread: false,
    avatarName: "Zoya Alvi",
    actorName: "Zoya Alvi",
    message: "closed an oversubscribed $850K Angel round for SolarGrid Energy",
    actions: ["congratulate"],
    tone: { background: "#F2705A", color: "#FFFFFF" },
  },
  {
    id: "n8",
    group: "This week",
    kind: "mention",
    category: "Mentions",
    timeAgo: "4d ago",
    unread: false,
    avatarName: "Farhan Tareen",
    actorName: "Farhan Tareen",
    message: "mentioned you in a deal discussion on HealthTech syndications",
    actions: [],
    linkLabel: "View discussion",
    tone: { background: "#3F4FA0", color: "#FFFFFF" },
  },
  {
    id: "n9",
    group: "Earlier",
    kind: "analytics",
    category: "Analytics",
    timeAgo: "6d ago",
    unread: false,
    avatarName: "Profile views",
    message: "Your profile was viewed by 6 verified investors this week",
    highlight: "6 verified investors",
    actions: [],
    linkLabel: "See who viewed",
  },
  {
    id: "n10",
    group: "Earlier",
    kind: "account",
    category: "Account",
    timeAgo: "1w ago",
    unread: false,
    avatarName: "Preferences",
    message:
      "Your investment preferences are incomplete. Add target sectors and ticket size to improve deal matches.",
    actions: ["add_preferences"],
  },
  {
    id: "n11",
    group: "Earlier",
    kind: "connection_accepted",
    category: "Connections",
    timeAgo: "2w ago",
    unread: false,
    avatarName: "Mirza Baig",
    actorName: "Mirza Baig",
    role: "Investor",
    message: "accepted your connection request",
    statusText: "You are now connected",
    actions: ["message"],
    tone: { background: "#7C5CBF", color: "#FFFFFF" },
    deferred: true,
  },
  {
    id: "n12",
    group: "Earlier",
    kind: "opportunity_interest",
    category: "Opportunities",
    timeAgo: "2w ago",
    unread: false,
    avatarName: "Dr. Rabia Mansoor",
    actorName: "Dr. Rabia Mansoor",
    role: "Founder",
    verified: true,
    message: "moved PulseHealth · Series A Extension to the Negotiation stage",
    highlight: "PulseHealth · Series A Extension",
    actions: ["view"],
    tone: { background: "#5BA4E6", color: "#FFFFFF" },
    deferred: true,
  },
  {
    id: "n13",
    group: "Earlier",
    kind: "milestone",
    category: "Milestones",
    timeAgo: "3w ago",
    unread: false,
    avatarName: "Sarah Jenkins",
    actorName: "Sarah Jenkins",
    role: "Investor",
    message: "published a new syndicated investment mandate for Q3 2026",
    actions: ["view"],
    tone: { background: "#F2705A", color: "#FFFFFF" },
    deferred: true,
  },
];