import {
  Brain,
  Briefcase,
  Building2,
  Code2,
  Cpu,
  Database,
  DollarSign,
  FileCode2,
  Globe,
  HardDrive,
  Laptop,
  Layers,
  Lightbulb,
  Lock,
  Mic,
  Network,
  Rocket,
  Sparkles,
  Terminal,
  TrendingUp,
  Workflow,
  Zap,
} from 'lucide-react'
import type {
  Category,
  ContinueItem,
  Episode,
  FeaturedEpisode,
  Show,
  ThumbnailVariant,
} from './types'

export const CATEGORIES: Category[] = [
  'All',
  'Founder stories',
  'Investor insights',
  'Deals closed',
  'Fundraising tips',
  'AgriTech',
  'FinTech',
  'HealthTech',
  'AI & Automation',
  'Legal & compliance',
  'Syndication',
]

export const THUMB_GRADIENTS: Record<ThumbnailVariant, string> = {
  indigo: 'linear-gradient(135deg, #14213D 0%, #2A2F78 100%)',
  violet: 'linear-gradient(135deg, #14213D 0%, #3B2F7A 100%)',
  deepBlue: 'linear-gradient(135deg, #14213D 0%, #1B2A5E 100%)',
  plum: 'linear-gradient(135deg, #14213D 0%, #34285F 100%)',
}

export const FEATURED_GRADIENT =
  'linear-gradient(105deg, #14213D 0%, #2A2F78 55%, #3B3F8F 100%)'

export const CARD_SHADOW =
  'shadow-[0_1px_2px_rgba(16,24,40,0.04),0_6px_20px_rgba(16,24,40,0.05)]'

export const CARD_SHADOW_HOVER =
  'hover:shadow-[0_4px_10px_rgba(16,24,40,0.06),0_12px_28px_rgba(16,24,40,0.09)]'

export const featuredEpisode: FeaturedEpisode = {
  id: 'featured-ai-gov-app',
  title: 'I Built a Government AI App in 30 Minutes: Tech Architecture & Code Breakdown',
  summary:
    'Raheel Siddiqui joins Muzamil Hasan to detail the tech stack, API orchestration, and low-latency LLM pipeline used to build a full government AI workflow in Pakistan.',
  hostName: 'Muzamil Hasan',
  hostTag: 'Host, TBT Podcast',
  guestName: 'Raheel Siddiqui',
  guestTag: 'AI Engineer & Builder',
  durationSeconds: 3120,
  publishedDaysAgo: 2,
  plays: 28400,
  topic: 'AI Architecture & Pakistan GovTech',
  icon: Brain,
  youtubeId: 'dGl9kYq5KKs',
}

export const continueItems: ContinueItem[] = [
  {
    id: 'continue-claude-code',
    title: 'STOP What You Are Doing and Learn Claude Code NOW!',
    host: 'Muzamil Hasan',
    episode: '24',
    percent: 65,
    minutesLeft: 11,
    durationSeconds: 2100,
    icon: Code2,
    variant: 'indigo',
  },
  {
    id: 'continue-ai-cloned-brain',
    title: 'I Cloned My Brain with AI: Complete Tech & Workflow Setup',
    host: 'Muzamil Hasan',
    episode: '19',
    percent: 42,
    minutesLeft: 18,
    durationSeconds: 1950,
    icon: Cpu,
    variant: 'deepBlue',
  },
  {
    id: 'continue-remote-tech-job',
    title: 'How to Land a Remote US Tech Job From Pakistan (Without a Degree)',
    host: 'Ghalib Hassam',
    episode: '31',
    percent: 80,
    minutesLeft: 6,
    durationSeconds: 2400,
    icon: Laptop,
    variant: 'plum',
  },
]

export const episodes: Episode[] = [
  {
    id: 'ep-pak-local-tech-market',
    title: '"Don\'t Build in Pakistan" - The Ugly Truth About the Local Tech Market',
    host: 'Maha Shahzad',
    role: 'Founder',
    plays: 34200,
    rating: 4.9,
    publishedDaysAgo: 3,
    durationSeconds: 3480,
    categories: ['Founder stories', 'AI & Automation'],
    icon: Building2,
    variant: 'indigo',
    shape: 'wave',
    accent: 'amber',
    youtubeId: '8AgLVQ42dMQ',
    description: 'An honest deep dive into SaaS margins, customer acquisition realities, B2B payment barriers, and engineering scale in Pakistan.',
  },
  {
    id: 'ep-pak-digital-rupee',
    title: "They Are Killing Cash: The Technical Reality of Pakistan's Digital Rupee",
    host: 'Ahmad Manzoor',
    role: 'Investor',
    plays: 41800,
    rating: 4.95,
    publishedDaysAgo: 5,
    durationSeconds: 3240,
    categories: ['FinTech', 'Investor insights'],
    icon: DollarSign,
    variant: 'violet',
    shape: 'circle',
    accent: 'sky',
    youtubeId: '5-53dibwMmQ',
    description: 'State Bank blockchain pilots, CBDC cryptographic validation, settlement APIs, and how digital rupees change fintech rails.',
  },
  {
    id: 'ep-freelancing-ecommerce-shift',
    title: 'Why "Building Shopify Sites" Won\'t Make You Money Anymore in 2026',
    host: 'Badar Munir',
    role: 'Founder',
    plays: 29500,
    rating: 4.85,
    publishedDaysAgo: 7,
    durationSeconds: 2910,
    categories: ['AI & Automation', 'Founder stories'],
    icon: Layers,
    variant: 'deepBlue',
    shape: 'triangle',
    accent: 'amber',
    youtubeId: 'WH9VZXYqN74',
    description: 'The shift from low-code web templates to custom headless architectures, AI-augmented development, and backend microservices.',
  },
  {
    id: 'ep-trap-pakistani-it-founder',
    title: 'The Trap Every Pakistani IT Founder Is Walking Into',
    host: 'Muzamil Hasan',
    role: 'Investor',
    plays: 26300,
    rating: 4.8,
    publishedDaysAgo: 8,
    durationSeconds: 2750,
    categories: ['Investor insights', 'Founder stories'],
    icon: Briefcase,
    variant: 'plum',
    shape: 'arc',
    accent: 'sky',
    youtubeId: '49Z1rx4OSlw',
    description: 'Service agency traps vs product incubation, equity structuring, and why Pakistani software houses struggle to build billion-dollar IP.',
  },
  {
    id: 'ep-5billion-secret-it-bosses',
    title: 'The $5 Billion Secret Pakistani IT Bosses Keep',
    host: 'Muzamil Hasan',
    role: 'Investor',
    plays: 38900,
    rating: 4.9,
    publishedDaysAgo: 10,
    durationSeconds: 3100,
    categories: ['Investor insights', 'Deals closed'],
    icon: TrendingUp,
    variant: 'indigo',
    shape: 'wave',
    accent: 'amber',
    youtubeId: 'nHGnUJpdT7E',
    description: 'Offshore billing, talent arbitrage, tech export incentives, and scaling Pakistani enterprise engineering teams to Fortune 500 accounts.',
  },
  {
    id: 'ep-ai-data-centers-pakistan',
    title: 'The Truth About Pakistan’s New High-Performance AI Data Centers',
    host: 'Muzamil Hasan',
    role: 'Investor',
    plays: 22100,
    rating: 4.75,
    publishedDaysAgo: 12,
    durationSeconds: 2840,
    categories: ['AI & Automation', 'Investor insights'],
    icon: HardDrive,
    variant: 'violet',
    shape: 'circle',
    accent: 'sky',
    youtubeId: '-jbGSb_i1qs',
    description: 'Analyzing server hardware capacity, cooling infrastructure, energy constraints, and sovereign GPU cloud potential in Pakistan.',
  },
  {
    id: 'ep-breaking-into-ai-no-coding',
    title: 'No Coding Background? How He Broke Into AI Engineering',
    host: 'Hashim Syed',
    role: 'Founder',
    plays: 45000,
    rating: 5.0,
    publishedDaysAgo: 14,
    durationSeconds: 3320,
    categories: ['AI & Automation', 'Founder stories'],
    icon: Cpu,
    variant: 'deepBlue',
    shape: 'arc',
    accent: 'amber',
    youtubeId: 'emEGz99UQxc',
    description: 'Prompt engineering pipelines, RAG architecture, vector databases, and how Pakistani developers can transition into machine learning.',
  },
  {
    id: 'ep-free-work-hack-us-job',
    title: 'The "Proof of Work" Strategy to Land a Remote US Tech Job from Pakistan',
    host: 'Ghalib Hassam',
    role: 'Founder',
    plays: 51200,
    rating: 4.95,
    publishedDaysAgo: 15,
    durationSeconds: 3180,
    categories: ['Founder stories', 'AI & Automation'],
    icon: Laptop,
    variant: 'plum',
    shape: 'wave',
    accent: 'sky',
    youtubeId: 'qQhHBMB1BNw',
    description: 'Building public GitHub repos, contributing to high-impact open source, and reverse-pitching US engineering directors directly.',
  },
  {
    id: 'ep-cloned-brain-ai-business',
    title: 'I Cloned My Brain with AI: End-to-End Automation for Modern Tech Work',
    host: 'Muzamil Hasan',
    role: 'Founder',
    plays: 33700,
    rating: 4.9,
    publishedDaysAgo: 17,
    durationSeconds: 2650,
    categories: ['AI & Automation', 'Founder stories'],
    icon: Workflow,
    variant: 'indigo',
    shape: 'circle',
    accent: 'amber',
    youtubeId: 'ler_YWhCET8',
    description: 'Connecting personal knowledge bases, multi-agent workflows, automated transcription, and agentic workflows for executives.',
  },
  {
    id: 'ep-dark-reality-of-ai',
    title: 'The Dark Reality of AI: Future of Software Engineering',
    host: 'Ahmad Awais',
    role: 'Founder',
    plays: 68400,
    rating: 5.0,
    publishedDaysAgo: 19,
    durationSeconds: 3750,
    categories: ['AI & Automation', 'Founder stories'],
    icon: Terminal,
    variant: 'violet',
    shape: 'triangle',
    accent: 'sky',
    youtubeId: 'yissMXL2dCc',
    description: 'VP & developer advocate Ahmad Awais reveals how AI models are rewriting the software engineering discipline and what devs must learn.',
  },
  {
    id: 'ep-learn-claude-code',
    title: 'STOP What You Are Doing and Master Agentic Coding & Claude Code',
    host: 'Muzamil Hasan',
    role: 'Founder',
    plays: 39600,
    rating: 4.95,
    publishedDaysAgo: 21,
    durationSeconds: 2280,
    categories: ['AI & Automation'],
    icon: FileCode2,
    variant: 'deepBlue',
    shape: 'wave',
    accent: 'amber',
    youtubeId: 'dWKLM805dDk',
    description: 'A hands-on breakdown of CLI-based autonomous agents, terminal integrations, and 10x developer workflows for Pakistani software engineers.',
  },
  {
    id: 'ep-spacetech-roadmap',
    title: 'The 10-Year Deep Tech & Space Tech Roadmap for Emerging Markets',
    host: 'Muzamil Hasan',
    role: 'Investor',
    plays: 19400,
    rating: 4.8,
    publishedDaysAgo: 22,
    durationSeconds: 3010,
    categories: ['Investor insights'],
    icon: Rocket,
    variant: 'plum',
    shape: 'circle',
    accent: 'sky',
    youtubeId: 'HiTloAtMj70',
    description: 'Hardware manufacturing, satellite connectivity, defense tech innovations, and venture capital opportunities in high-frontier tech.',
  },
  {
    id: 'ep-spacex-vs-ai-bubble',
    title: 'AI Valuation Bubbles vs Deep Infrastructure: Market Corrections',
    host: 'Muzamil Hasan',
    role: 'Investor',
    plays: 31500,
    rating: 4.85,
    publishedDaysAgo: 24,
    durationSeconds: 3410,
    categories: ['Investor insights', 'FinTech'],
    icon: Sparkles,
    variant: 'indigo',
    shape: 'triangle',
    accent: 'amber',
    youtubeId: 'ctPtrpuz-t8',
    description: 'Analyzing semiconductor capex, software multiples, venture capital dry powder, and macroeconomic tailwinds affecting tech investments.',
  },
  {
    id: 'ep-freelancer-banking-fx',
    title: 'Pakistani Freelancers & Tech Firms: FX Compliance & Offshore Banking',
    host: 'Muzamil Hasan',
    role: 'Legal Partner',
    plays: 57800,
    rating: 4.9,
    publishedDaysAgo: 25,
    durationSeconds: 2790,
    categories: ['Legal & compliance', 'FinTech'],
    icon: Lock,
    variant: 'violet',
    shape: 'arc',
    accent: 'sky',
    youtubeId: 'mr6qOvbVLRw',
    description: 'SBP FE circulars, exporter retention accounts, Payoneer vs direct wire protocols, tax filings, and safeguarding USD balances legally.',
  },
  {
    id: 'ep-remote-us-tech-job-no-degree',
    title: 'How to Land a Remote US Software Engineering Role (Without a CS Degree)',
    host: 'Muzamil Hasan',
    role: 'Founder',
    plays: 64100,
    rating: 4.95,
    publishedDaysAgo: 26,
    durationSeconds: 3120,
    categories: ['Founder stories', 'AI & Automation'],
    icon: Code2,
    variant: 'deepBlue',
    shape: 'wave',
    accent: 'amber',
    youtubeId: 'pkRdy5uscus',
    description: 'System design interview prep, portfolio building, live coding assessments, and negotiating 6-figure USD compensation packages.',
  },
  {
    id: 'ep-meezan-bank-fintech-illusion',
    title: 'Islamic Finance Architecture & Digital Core Banking in Pakistan',
    host: 'Muzamil Hasan',
    role: 'Investor',
    plays: 48200,
    rating: 4.85,
    publishedDaysAgo: 28,
    durationSeconds: 3620,
    categories: ['FinTech', 'Investor insights'],
    icon: Building2,
    variant: 'plum',
    shape: 'circle',
    accent: 'sky',
    youtubeId: 'I6zI57zc7WE',
    description: 'Evaluating Shariah-compliant digital lending algorithms, core banking migration, micro-transactions, and modern fintech rails.',
  },
  {
    id: 'ep-chatgpt-top-5-industries',
    title: 'The Top 5 Tech Industries Primed for Disruption in the Next 25 Years',
    host: 'Muzamil Hasan',
    role: 'Investor',
    plays: 35900,
    rating: 4.8,
    publishedDaysAgo: 29,
    durationSeconds: 2890,
    categories: ['AI & Automation', 'Investor insights'],
    icon: Lightbulb,
    variant: 'indigo',
    shape: 'wave',
    accent: 'amber',
    youtubeId: '9BtDvkw--5k',
    description: 'Predictive analytics on robotics, synthetic biology, autonomous logistics, personalized education, and decentralized computational networks.',
  },
  {
    id: 'ep-youtubification-of-software',
    title: 'The "YouTubification" of Software: AI\'s Trillion-Dollar Architectural Shift',
    host: 'Muzamil Hasan',
    role: 'Founder',
    plays: 42100,
    rating: 4.9,
    publishedDaysAgo: 30,
    durationSeconds: 2950,
    categories: ['AI & Automation', 'Founder stories'],
    icon: Database,
    variant: 'violet',
    shape: 'triangle',
    accent: 'sky',
    youtubeId: 'crMXq1RPYas',
    description: 'Why individual software developers now possess the capability of entire engineering departments and how micro-SaaS will proliferate.',
  },
  {
    id: 'ep-us-remote-job-step-by-step',
    title: 'Landing a High-Ticket US Remote Tech Job from Pakistan: Step-by-Step Guide',
    host: 'Ghalib Hassam',
    role: 'Founder',
    plays: 53900,
    rating: 4.95,
    publishedDaysAgo: 32,
    durationSeconds: 3290,
    categories: ['Founder stories', 'AI & Automation'],
    icon: Laptop,
    variant: 'deepBlue',
    shape: 'arc',
    accent: 'amber',
    youtubeId: 'mDny-EeuzP4',
    description: 'From resume optimization with ATS parsers to asynchronous video screenings and technical round mastery for global engineering roles.',
  },
  {
    id: 'ep-stop-panicking-about-ai',
    title: 'Stop Panicking About AI: Historical Tech Booms and The Next Software Wave',
    host: 'Muzamil Hasan',
    role: 'Investor',
    plays: 28700,
    rating: 4.8,
    publishedDaysAgo: 34,
    durationSeconds: 2710,
    categories: ['AI & Automation', 'Investor insights'],
    icon: Zap,
    variant: 'plum',
    shape: 'wave',
    accent: 'sky',
    youtubeId: '4hww6Fsgfdg',
    description: 'Lessons from the PC revolution, internet bubble, and cloud transition: why builders who leverage new tooling thrive while laggards decline.',
  },
  {
    id: 'ep-china-free-ai-strategy',
    title: 'Open Source AI Models vs Proprietary Giants: China’s Global Tech Play',
    host: 'Muzamil Hasan',
    role: 'Investor',
    plays: 31000,
    rating: 4.85,
    publishedDaysAgo: 36,
    durationSeconds: 3040,
    categories: ['AI & Automation', 'Investor insights'],
    icon: Globe,
    variant: 'indigo',
    shape: 'circle',
    accent: 'amber',
    youtubeId: 'mDilCHv27Hg',
    description: 'DeepSeek, open weights LLMs, edge inference efficiency, and what access to commoditized high-performance AI means for Pakistani developers.',
  },
  {
    id: 'ep-seo-tanveer-nandla',
    title: 'Algorithmic Search & Scaling Tech Products to $70,000/Month',
    host: 'M. Tanveer Nandla',
    role: 'Founder',
    plays: 47600,
    rating: 4.9,
    publishedDaysAgo: 38,
    durationSeconds: 3380,
    categories: ['Founder stories', 'AI & Automation'],
    icon: Network,
    variant: 'violet',
    shape: 'triangle',
    accent: 'sky',
    youtubeId: 'Uf0BfM0SIqo',
    description: 'Search intent algorithms, programmatic programmatic SEO with automated pipelines, and building sustainable recurring revenue from Pakistan.',
  },
]

export const shows: Show[] = [
  { id: 'show-tbt-podcast', name: 'Thought Behind Things (TBT)', host: 'Muzamil Hasan', icon: Mic },
  { id: 'show-dil-ki-baat', name: 'Dil Ki Baat (Tech & Macro)', host: 'Muzamil Hasan', icon: Lightbulb },
  { id: 'show-tech-founders-pk', name: 'Pakistan Tech Founders', host: 'Ghalib Hassam', icon: Code2 },
  { id: 'show-ai-builders-pk', name: 'AI Builders & Systems', host: 'Ahmad Awais', icon: Brain },
]

export const DEFAULT_FOLLOWED: string[] = ['show-tbt-podcast']

export function formatClock(totalSeconds: number): string {
  const seconds = Math.max(0, Math.round(totalSeconds))
  const minutes = Math.floor(seconds / 60)
  const rest = seconds % 60
  return `${minutes}:${String(rest).padStart(2, '0')}`
}

export function formatPlays(plays: number): string {
  if (plays < 1000) return String(plays)
  const value = Math.round((plays / 1000) * 10) / 10
  const label = value % 1 === 0 ? value.toFixed(0) : value.toFixed(1)
  return `${label}K`
}

export function formatPublishedDays(days: number): string {
  if (days < 7) return `${days}d ago`
  if (days < 30) return `${Math.round(days / 7)}w ago`
  return `${Math.round(days / 30)}mo ago`
}
