import type { Mandate, Raise } from "./types";

const NAVY = { bg: "#14213D", fg: "#FFFFFF" };
const VIOLET = { bg: "#4B3A8F", fg: "#FFFFFF" };
const CORAL = { bg: "#E4573D", fg: "#FFFFFF" };
const BLUE = { bg: "#3567C9", fg: "#FFFFFF" };
const AMBER = { bg: "#F5B544", fg: "#14213D" };
const DEEP = { bg: "#1B2150", fg: "#FFFFFF" };
const PURPLE = { bg: "#5B3FA0", fg: "#FFFFFF" };
const early = { text: "Be an early responder", tinted: true };
const fast = { text: "Fast decision track", tinted: true };

export const MANDATES: Mandate[] = [
  { id: "m1", initials: "AC", ...NAVY, title: "Seed to Series A FinTech Mandate", investor: "Apex Capital Syndicate", subtitle: "Apex Capital Syndicate · Lahore · Remote friendly", chips: ["Ticket PKR 20M to 80M", "Co-invest OK", "FinTech, AgriTech"], sectors: ["FinTech", "AgriTech"], stages: ["Seed", "Series A"], region: "Pakistan", ticketMinM: 20, ticketMaxM: 80, thesis: "Backing foundational B2B payment rails and financial infrastructure modernizing trade in Pakistan & MENA.", recent: ["TriadPay (Seed)", "KissanCred (Series A)", "BridgePOS (Seed)"], postedAgo: "2 days ago", tag: early },
  { id: "m2", initials: "IH", ...VIOLET, title: "Early Stage DeepTech & AI Fund", investor: "Indus Horizon Capital", subtitle: "Indus Horizon Capital · Karachi · Hybrid", chips: ["Ticket PKR 30M to 120M", "Lead investor mandate", "AI, Data"], sectors: ["DeepTech & AI"], stages: ["Seed", "Series A"], region: "Pakistan", ticketMinM: 30, ticketMaxM: 120, thesis: "Leading first institutional rounds for applied AI teams building proprietary data advantages.", recent: ["VisionLoom (Seed)", "DataKhazana (Series A)"], postedAgo: "1 day ago", tag: fast },
  { id: "m3", initials: "KA", ...CORAL, title: "Pre-Seed AgriTech Syndicate Allocation", investor: "Karakoram Angels", subtitle: "Karakoram Angels · Islamabad · In-person syncs", chips: ["Ticket PKR 15M to 45M", "Syndicate 12 angels", "AgriTech, Supply Chain"], sectors: ["AgriTech", "Logistics"], stages: ["Pre-seed", "Seed"], region: "Pakistan", ticketMinM: 15, ticketMaxM: 45, thesis: "Pooling angel capital behind founders who digitise farm-to-market supply chains.", recent: ["MandiLink (Pre-seed)", "SoilSense (Seed)"], postedAgo: "3 days ago", tag: { text: "6 pitches submitted", tinted: false } },
  { id: "m4", initials: "CM", ...BLUE, title: "Series A HealthTech Growth Facility", investor: "Crescent Moon Ventures", subtitle: "Crescent Moon Ventures · Lahore & Dubai", chips: ["Ticket PKR 50M to 150M", "Growth debt + equity", "HealthTech"], sectors: ["HealthTech"], stages: ["Series A", "Growth"], region: "Both", ticketMinM: 50, ticketMaxM: 150, thesis: "Funding clinical networks and care-delivery platforms with proven unit economics.", recent: ["ShifaConnect (Series A)", "LabLink (Growth)"], postedAgo: "4 days ago", tag: early },
  { id: "m5", initials: "MI", ...DEEP, title: "Seed CleanTech Impact Mandate", investor: "Meridian Impact Partners", subtitle: "Meridian Impact Partners · Dubai · Remote friendly", chips: ["Ticket PKR 25M to 90M", "Impact reporting", "CleanTech"], sectors: ["CleanTech"], stages: ["Seed", "Series A"], region: "GCC", ticketMinM: 25, ticketMaxM: 90, thesis: "Backing distributed energy and water-efficiency companies with measurable emissions impact.", recent: ["WattShare (Seed)", "DrySpin (Series A)", "SunLedger (Seed)"], postedAgo: "5 days ago", tag: early },
  { id: "m6", initials: "GF", ...BLUE, title: "Growth Stage Logistics Platform Fund", investor: "Gulf Frontier Fund", subtitle: "Gulf Frontier Fund · Abu Dhabi & Karachi · Hybrid", chips: ["Ticket PKR 80M to 200M", "Board seat", "Logistics"], sectors: ["Logistics"], stages: ["Series A", "Growth"], region: "Both", ticketMinM: 80, ticketMaxM: 200, thesis: "Scaling cross-border freight and warehousing platforms across the Gulf-Pakistan corridor.", recent: ["CargoBridge (Series A)", "PortPilot (Growth)"], postedAgo: "5 days ago", tag: fast },
  { id: "m7", initials: "MA", ...CORAL, title: "Pre-Seed Commerce & Payments Angels", investor: "Margalla Angels", subtitle: "Margalla Angels · Islamabad · Remote friendly", chips: ["Ticket PKR 5M to 25M", "Angel syndicate", "FinTech, Logistics"], sectors: ["FinTech", "Logistics"], stages: ["Pre-seed"], region: "Pakistan", ticketMinM: 5, ticketMaxM: 25, thesis: "Writing first cheques for founders with early traction in retail payments and delivery.", recent: ["DukaanPay (Pre-seed)", "RiderOne (Pre-seed)"], postedAgo: "6 days ago", tag: { text: "9 pitches submitted", tinted: false } },
  { id: "m8", initials: "SR", ...PURPLE, title: "Seed HealthTech Clinic Networks Mandate", investor: "Salt Range Capital", subtitle: "Salt Range Capital · Lahore · In-person syncs", chips: ["Ticket PKR 20M to 60M", "Operator support", "HealthTech"], sectors: ["HealthTech"], stages: ["Seed"], region: "Pakistan", ticketMinM: 20, ticketMaxM: 60, thesis: "Investing in software that makes independent clinics and diagnostics labs run better.", recent: ["ClinicOS (Seed)", "RxRoute (Seed)"], postedAgo: "1 week ago", tag: early },
  { id: "m9", initials: "KT", ...NAVY, title: "Series A Industrial AI Mandate", investor: "Karachi Tide Partners", subtitle: "Karachi Tide Partners · Karachi · Hybrid", chips: ["Ticket PKR 60M to 140M", "Lead or co-lead", "AI, Manufacturing"], sectors: ["DeepTech & AI"], stages: ["Series A"], region: "Pakistan", ticketMinM: 60, ticketMaxM: 140, thesis: "Applied machine learning for factories, ports and heavy industry with enterprise contracts.", recent: ["LoomVision (Series A)", "YardIQ (Series A)", "SteelSense (Seed)"], postedAgo: "1 week ago", tag: fast },
  { id: "m10", initials: "OG", ...VIOLET, title: "Growth Debt for Profitable FinTechs", investor: "Oasis Growth Partners", subtitle: "Oasis Growth Partners · Riyadh · Remote friendly", chips: ["Ticket PKR 100M to 300M", "Venture debt", "FinTech"], sectors: ["FinTech"], stages: ["Growth"], region: "GCC", ticketMinM: 100, ticketMaxM: 300, thesis: "Non-dilutive capital for cash-flow-positive lenders and payment processors scaling regionally.", recent: ["QistPay (Growth)", "RemitNest (Growth)"], postedAgo: "1 week ago", tag: { text: "4 pitches submitted", tinted: false } },
  { id: "m11", initials: "HS", ...AMBER, title: "Pre-Seed CleanTech & AgriTech Collective", investor: "Hunza Seed Collective", subtitle: "Hunza Seed Collective · Gilgit & Lahore · In-person", chips: ["Ticket PKR 10M to 30M", "Mentor network", "CleanTech, AgriTech"], sectors: ["CleanTech", "AgriTech"], stages: ["Pre-seed"], region: "Pakistan", ticketMinM: 10, ticketMaxM: 30, thesis: "Early capital for mountain-region founders solving energy and food-security problems.", recent: ["GlacierGrid (Pre-seed)", "OrchardOS (Pre-seed)"], postedAgo: "2 weeks ago", tag: early },
  { id: "m12", initials: "DB", ...BLUE, title: "Seed to Series A Cross-Border Logistics", investor: "Doha Bridge Capital", subtitle: "Doha Bridge Capital · Doha · Hybrid", chips: ["Ticket PKR 40M to 110M", "Co-invest OK", "Logistics"], sectors: ["Logistics"], stages: ["Seed", "Series A"], region: "GCC", ticketMinM: 40, ticketMaxM: 110, thesis: "Backing trade-tech teams that cut customs and freight friction between Pakistan and the Gulf.", recent: ["CustomsKit (Seed)", "HaulHub (Series A)"], postedAgo: "2 weeks ago", tag: fast },
];

export const RAISES: Raise[] = [
  { id: "r1", initials: "AF", ...AMBER, title: "AgriFlow · Seed Round", company: "AgriFlow", subtitle: "AgriTech · Lahore · Pre-seed to Seed", sectors: ["AgriTech"], stages: ["Pre-seed", "Seed"], region: "Pakistan", pitch: "Cold-chain IoT telemetry and inventory financing for smallholder farmers.", raisedM: 48, targetM: 120, minTicketM: 5, interested: 42, interestedBy: ["IV", "SA", "MK"], closingDays: 18, postedAgo: "15 hours ago", founders: "Tariq Mansoor (CEO, ex-Careem) · Dr. Amina Sheikh (CTO, IoT PhD)", traction: "Previous: PKR 25M Pre-Seed led by Indus Valley Syndicate. Current metrics: PKR 14M ARR, 180% YoY grower retention." },
  { id: "r2", initials: "PH", ...DEEP, title: "PulseHealth · Series A Extension", company: "PulseHealth", subtitle: "HealthTech · Karachi · Clinical AI", sectors: ["HealthTech", "DeepTech & AI"], stages: ["Series A"], region: "Pakistan", pitch: "AI-guided triage and diagnostic triage workflow for secondary care clinics.", raisedM: 82, targetM: 100, minTicketM: 10, interested: 58, interestedBy: ["RK", "NA", "ZH"], closingDays: 6, postedAgo: "1 day ago", founders: "Dr. Hira Baig (CEO, ex-Aga Khan) · Salman Qureshi (CTO, ML lead)", traction: "Live in 46 clinics. PKR 31M ARR, 94% clinician weekly retention." },
  { id: "r3", initials: "LF", ...NAVY, title: "LogiFleet AI · Pre-Series A", company: "LogiFleet AI", subtitle: "Logistics & AI · Islamabad · B2B Freight", sectors: ["Logistics", "DeepTech & AI"], stages: ["Seed", "Series A"], region: "Pakistan", pitch: "Autonomous dispatch & cargo pooling engine across Pakistan cross-country corridors.", raisedM: 35, targetM: 75, minTicketM: 5, interested: 29, interestedBy: ["FA", "BT"], closingDays: 24, postedAgo: "2 days ago", founders: "Usman Tariq (CEO, ex-Daraz) · Mehreen Ali (CTO, optimisation PhD)", traction: "Pooled 11,000 loads in 2025. PKR 9M MRR with 3 enterprise shippers." },
  { id: "r4", initials: "SG", ...PURPLE, title: "SolarGrid Energy · Seed Bridge", company: "SolarGrid Energy", subtitle: "CleanTech · Faisalabad · Microgrids", sectors: ["CleanTech"], stages: ["Seed"], region: "Pakistan", pitch: "Decentralized solar micro-utilities powering industrial textile clusters.", raisedM: 60, targetM: 90, minTicketM: 8, interested: 36, interestedBy: ["HQ", "TM"], closingDays: 12, postedAgo: "3 days ago", founders: "Bilal Ahmed (CEO, ex-K-Electric) · Sana Rauf (COO, project finance)", traction: "14 MW contracted across 9 mills. Payback under 4 years per site." },
  { id: "r5", initials: "AP", ...BLUE, title: "AquaPure Systems · Seed Round", company: "AquaPure Systems", subtitle: "CleanTech · Multan · Water Reuse", sectors: ["CleanTech"], stages: ["Seed"], region: "Pakistan", pitch: "Water treatment and reuse units for textile dyeing facilities.", raisedM: 18, targetM: 60, minTicketM: 5, interested: 24, interestedBy: ["AJ", "KN", "OM"], closingDays: 9, postedAgo: "4 days ago", founders: "Faisal Nadeem (CEO, chemical engineer) · Dr. Rabia Saleem (CTO)", traction: "6 plants live, 38% average water recovered. PKR 7M ARR." },
  { id: "r6", initials: "KP", ...CORAL, title: "KhataBook Pro · Seed Extension", company: "KhataBook Pro", subtitle: "FinTech · Lahore · Retail Credit", sectors: ["FinTech"], stages: ["Seed"], region: "Pakistan", pitch: "Digital ledgers and credit scoring for kiryana retailers.", raisedM: 40, targetM: 55, minTicketM: 5, interested: 61, interestedBy: ["SB", "WQ", "LD"], closingDays: 5, postedAgo: "5 days ago", founders: "Areeba Khan (CEO, ex-JazzCash) · Hamza Javed (CTO)", traction: "120,000 active merchants. PKR 11M ARR, 2.1% default rate." },
  { id: "r7", initials: "NL", ...VIOLET, title: "NeuroLens Labs · Series A", company: "NeuroLens Labs", subtitle: "DeepTech & AI · Karachi · Machine Vision", sectors: ["DeepTech & AI"], stages: ["Series A"], region: "Pakistan", pitch: "Computer-vision quality inspection for garment manufacturers.", raisedM: 90, targetM: 200, minTicketM: 20, interested: 33, interestedBy: ["TS", "EG"], closingDays: 30, postedAgo: "5 days ago", founders: "Dr. Omar Siddiqui (CEO, vision PhD) · Nida Farooq (CRO, ex-Interloop)", traction: "Deployed on 210 production lines. PKR 52M ARR, 130% net revenue retention." },
  { id: "r8", initials: "FR", ...AMBER, title: "FreshRoute · Pre-seed Round", company: "FreshRoute", subtitle: "Logistics · Rawalpindi · Cold Chain", sectors: ["Logistics", "AgriTech"], stages: ["Pre-seed"], region: "Pakistan", pitch: "Cold-chain last-mile delivery marketplace for perishable goods.", raisedM: 12, targetM: 40, minTicketM: 2, interested: 17, interestedBy: ["YP", "CZ"], closingDays: 21, postedAgo: "6 days ago", founders: "Danish Iqbal (CEO, ex-Foodpanda) · Laiba Shah (Ops)", traction: "420 daily deliveries, 97% on-time. PKR 3M monthly GMV growth." },
  { id: "r9", initials: "MH", ...DEEP, title: "MediBridge Health · Seed Round", company: "MediBridge Health", subtitle: "HealthTech · Lahore · Telemedicine", sectors: ["HealthTech"], stages: ["Seed"], region: "Pakistan", pitch: "Telemedicine and pharmacy fulfillment for tier-2 cities.", raisedM: 28, targetM: 50, minTicketM: 4, interested: 44, interestedBy: ["GN", "PR", "JD"], closingDays: 14, postedAgo: "1 week ago", founders: "Dr. Kashif Mehmood (CEO) · Zoya Anwar (CPO, ex-Sehat Kahani)", traction: "85,000 consultations to date. Pharmacy margin 18%, 4.7 app rating." },
  { id: "r10", initials: "HP", ...NAVY, title: "HarvestPay · Series A", company: "HarvestPay", subtitle: "FinTech & AgriTech · Karachi · Embedded Finance", sectors: ["FinTech", "AgriTech"], stages: ["Series A"], region: "Pakistan", pitch: "Embedded payments and input financing for agri-input dealers.", raisedM: 110, targetM: 150, minTicketM: 15, interested: 52, interestedBy: ["VM", "KS", "BH"], closingDays: 7, postedAgo: "1 week ago", founders: "Ayesha Mirza (CEO, ex-HBL) · Rohail Dar (CTO, payments)", traction: "PKR 2.3B processed in 2025. 1.4% take rate, 8,000 dealers." },
  { id: "r11", initials: "TC", ...PURPLE, title: "TerraCharge · Seed Bridge", company: "TerraCharge", subtitle: "CleanTech · Dubai & Lahore · EV Charging", sectors: ["CleanTech", "Logistics"], stages: ["Seed"], region: "Both", pitch: "EV charging network software for fleet operators.", raisedM: 22, targetM: 45, minTicketM: 5, interested: 19, interestedBy: ["AQ", "LM"], closingDays: 28, postedAgo: "1 week ago", founders: "Hassan Raza (CEO, ex-Careem) · Mariam Tahir (CTO, embedded systems)", traction: "310 chargers managed across 4 fleets. PKR 6M ARR." },
  { id: "r12", initials: "SL", ...CORAL, title: "Sutra Learn · Growth Round", company: "Sutra Learn", subtitle: "DeepTech & AI · Islamabad · EdTech AI", sectors: ["DeepTech & AI"], stages: ["Growth"], region: "Pakistan", pitch: "Adaptive tutoring engine for vernacular-language schools.", raisedM: 150, targetM: 300, minTicketM: 25, interested: 71, interestedBy: ["BN", "UF", "QA"], closingDays: 35, postedAgo: "2 weeks ago", founders: "Dr. Sadia Hussain (CEO, learning scientist) · Taimoor Ali (CTO)", traction: "340 partner schools, 210,000 learners. PKR 88M ARR." },
];
